apps/mentee/urls.py
from django.conf.urls import patterns, url
from apps.mentee import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^register/$', views.register, name='index'),
                       url(r'^requests/$', views.requests, name='requests'),
                       url(r'^self-profile/$', views.self_profile_view, name="self_profile_view"),
                       url(r'^edit-profile/$', views.edit_profile, name="edit_profile"),
                       url(r'^get-data/$', views.get_data, name="get_data"),
                       url(r'^manage-social-profiles/(?P<action>\w+)/(?P<provider>\w+)/$', views.manage_social_profiles,
                           name="remove-social-profiles"),
                       url(r'^manage-social-profiles/$', views.manage_social_profiles, name="manage-social-profiles"))

mentorbuddy/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
import apps
admin.autodiscover()

urlpatterns = patterns('',
                       url('', include('social.apps.django_app.urls', namespace='social')),
                       url(r'^$', include('apps.user.urls')),
                       url(r'^user/', include('apps.user.urls')),
                       url(r'^mentor/', include('apps.mentor.urls')),
                       url(r'^mentee/', include('apps.mentee.urls')),
                       url(r'^live/', include('apps.sinch.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^search/', include('apps.user.urls')),
                       url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

                       url(r'^sedna/$', apps.user.views.bmentor_index, name='sedna'),
                       url(r'^edu/$', apps.user.views.index, name='edu_page')


                       )

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)',
         'serve',
         {'document_root': settings.MEDIA_ROOT}), )

apps/mentee/models.py
from django.db import models
from django.contrib.auth.models import User


class Credits(models.Model):
    """Stores employment details of the user"""

    parent = models.OneToOneField(User, related_name="credits", primary_key=True)
    balance = models.FloatField(blank=True, default=5.0)

    def __unicode__(self):
        return u'{}'.format(self.parent.get_full_name())
        # return u'{2} in {1} of {0} from {3} to {4}'.format(self.organization,
        # self.department, self.designation, self.from_date, "present" if not self.to_date else self.to_date)

    class Meta:
        verbose_name = verbose_name_plural = "Credits"

apps/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
# for django-allauth signals
from allauth.account.signals import user_logged_in, user_signed_up
import datetime

# for upload_to
from django.utils import timezone

from django.utils.deconstruct import deconstructible
from mentorbuddy import settings
import os

from haystack.forms import SearchForm

import apps.user.fields

# http://stackoverflow.com/questions/25767787/django-cannot-create-migrations-for-imagefield-with-dynamic-upload-to-value


@deconstructible
class PathAndRename(object):
    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        # set filename as random string
        filename = '{}.{}'.format(instance.user.username, ext)
        # return the whole path to the file
        newPath = os.path.join(settings.MEDIA_ROOT, "resume")
        if not os.path.exists(newPath):
            os.makedirs(newPath)

        return os.path.join(newPath, instance.user.username + "." + ext)


path_and_rename = PathAndRename("/resume/")


class UserProfile(models.Model):
    @staticmethod
    def generate_new_filename(instance, filename):
        f, ext = os.path.splitext(filename)
        return '%s%s' % (instance.user.username, ext)

    """Associates the User with a 'Profile'."""

    # Stores username, password, first_name, last_name, email
    user = models.OneToOneField(User, related_name="user_profile", editable=False,
                                primary_key=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M', blank=True)
    date_of_birth = models.DateField(blank=True, null=True)
    contact = models.CharField(max_length=128, blank=True)
    college = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=128, blank=True)
    state = models.CharField(max_length=128, blank=True)
    country = models.CharField(max_length=128, blank=True)
    about = models.TextField(blank=True)
    resume = models.FileField(upload_to=path_and_rename, null=True, blank=True)
    picture = models.CharField(max_length=256, default='/static/img/no-profile-pic.jpg')  # Contains URL
    is_mentor = models.BooleanField(default=False)
    is_bmentor = models.BooleanField(default=False)
    is_new = models.BooleanField(default=True)
    is_approved = models.BooleanField(default=False)
    email_verified = models.BooleanField(default=False)
    timezone = models.CharField(max_length=256, null=True, default=None)

    def full_name(self):
        return self.user.get_full_name()

    def __unicode__(self):
        email = self.user.email
        if email:
            return email
        else:
            return self.user.username

    class Meta:
        verbose_name = "User Profile"

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile = UserProfile.objects.create(user=instance)


    models.signals.post_save.connect(create_user_profile, sender=User)


class SocialProfile(models.Model):
    """Stores social profile urls of the user"""

    parent = models.OneToOneField(UserProfile, related_name="social_profiles",
                                  editable=False)
    # we may need other social urls for later use
    profile_url_facebook = models.URLField(max_length=256, blank=True, default='')
    profile_url_linkedin = models.URLField(max_length=256, blank=True, default='')
    profile_url_twitter = models.URLField(max_length=256, blank=True, default='')
    profile_url_google = models.URLField(max_length=256, blank=True, default='')
    profile_url_github = models.URLField(max_length=256, blank=True, default='')

    profile_pic_url_facebook = models.URLField(max_length=256, blank=True, default='')
    profile_pic_url_linkedin = models.URLField(max_length=256, blank=True, default='')
    profile_pic_url_google = models.URLField(max_length=256, blank=True, default='')
    profile_pic_url_github = models.URLField(max_length=256, blank=True, default='')
    profile_pic_url_twitter = models.URLField(max_length=256, blank=True, default='')

    def __unicode__(self):
        return u"Social Profiles - {0}".format(self.parent.full_name())

    class Meta:
        verbose_name = verbose_name_plural = "Social Profiles"


class MentorSearchForm(SearchForm):
    def no_query_found(self):
        return self.searchqueryset.all()

    def search(self):
        # First, store the SearchQuerySet received from other processing. (the main work is run internally by Haystack here).
        sqs = super(MentorSearchForm, self).search()

        # if something goes wrong
        if not self.is_valid():
            return self.no_query_found()

        # you can then adjust the search results and ask for instance to order the results by title
        # sqs = sqs.order_by(city)

        return sqs


class Request(models.Model):
    menteeId = models.ForeignKey(User, related_name="requestsMade", blank=False)
    mentorId = models.ForeignKey(User, related_name="requestsReceived", blank=False)
    dateTime = models.DateTimeField(blank=False, default=datetime.datetime.now)
    # time = models.TimeField(blank=False, default=datetime.datetime.now)
    duration = apps.user.fields.IntegerRangeField(min_value=1, max_value=30)
    is_approved = models.NullBooleanField(default=None, null=True)
    is_rescheduled = models.BooleanField(default=False)
    requestDate = models.DateField(blank=False, default=datetime.date.today)
    callType = apps.user.fields.IntegerRangeField(min_value=1, max_value=3, default=1)
    is_completed = models.BooleanField(default=False)
    message = models.TextField(blank=True, null=True)
    class Meta:
        verbose_name = "Request"

    def __unicode__(self):
        request_name = User.objects.get(id=self.menteeId_id).first_name + " to " + User.objects.get(
            id=self.mentorId_id).first_name + " for " + str(self.dateTime.date())
        if request_name:
            return request_name
        else:
            return self.id


class CallLog(models.Model):
    request = models.OneToOneField(Request, related_name="callLog", primary_key=True)
    establishedTime = models.TimeField(blank=False, default=datetime.datetime.now)
    endTime = models.TimeField(blank=False, default=datetime.datetime.now)
    duration = apps.user.fields.IntegerRangeField(default=0, min_value=5, max_value=30, verbose_name="Duration(sec)")
    endCause = models.CharField(max_length=20)

    class Meta:
        verbose_name = "Call Log"

    def __unicode__(self):
        request_name = User.objects.get(id=self.request.menteeId_id).first_name + " to " + User.objects.get(
            id=self.request.mentorId_id).first_name + " on " + str(self.request.dateTime.date().strftime("%d-%m-%y"))
        if request_name:
            return request_name
        else:
            return self.id


class Feedback(models.Model):
    """"Stores Feedback for every call """""
    user = models.ForeignKey(User, editable=False)
    call = models.ForeignKey(CallLog, related_name='feedback', editable=False)
    rating = models.FloatField(null=False, default=0.0, blank=False)
    feedback = models.CharField(max_length=512, null=False, blank=True)

    class Meta:
        verbose_name = "Feedback"

    def __unicode__(self):
        user = self.user.get_full_name()
        return "from " + user


class VerificationCodes(models.Model):
    user = models.OneToOneField(User, related_name="verification", primary_key=True)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(auto_now_add=False)

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name_plural = u'VerificationCodes'


class Notification(models.Model):
    to = models.ForeignKey(User, related_name="notifications")
    frm = models.CharField(max_length=300, null=True, blank=True)  # from is reserved keyword
    text = models.TextField(blank=True, max_length=300, null=True)
    title = models.CharField(blank=True, max_length=500, null=False)
    dateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.to.get_full_name()

    class Meta:
        verbose_name_plural = u'Notifications'


class Todo(models.Model):
    parent = models.ForeignKey(User, related_name="tasks")
    task = models.TextField(blank=True, max_length=300, null=True)
    dateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{0}-{1}".format(self.task, self.parent)

    class Meta:
        verbose_name_plural = u'Todo List'


class Question(models.Model):
    question = models.TextField(null=False)

    class Meta:
        verbose_name_plural = "Questions"


class Answer(models.Model):
    question = models.ForeignKey(Question)
    answer = models.TextField(null=False, blank=True)
    mentor = models.ForeignKey(User, related_name='answer', null=False)
    class Meta:
        verbose_name_plural = "Answers"

apps/mentee/forms.py
from django import forms
from django.contrib.auth.models import User
from apps.user.models import UserProfile


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('gender', 'date_of_birth', 'contact', 'college', 'city', 'state', 'country', 'about', 'picture')
        widgets = {
            'about': forms.Textarea(attrs={'rows': 2}),
            'contact': forms.TextInput(attrs={'placeholder': 'eg +91 9970631445'}),
            'date_of_birth': forms.DateInput(attrs={'placeholder': 'MM/DD/YYYY'}, format="%m/%d/%Y"),
            'city': forms.TextInput(attrs={'placeholder': 'Mumbai'}),
            'country': forms.TextInput(attrs={'placeholder': 'India'}),
            'state': forms.TextInput(attrs={'placeholder': 'Maharashtra'})
        }

templates/mentee/edit_profile.html
{% extends 'mentee/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block stylesheets %}

    <link href="{% static 'css/mentee/edit-profile.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'datepicker/css/datepicker.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jcrop/imgareaselect-default.css' %}" />


{%  endblock %}
{% block topLevel %}
      <!-- Image Crop Modal -->
      <div class="modal fade" id="cropModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">Set a Profile Picture</h4>
            </div>
            <div class="modal-body">
              <div class="row">
                <div class="col-xs-12">
                  <form id="uploadForm" method="POST" action="/user/save-image/" enctype="multipart/form-data">
                    {% csrf_token %}
                     <div class="form-group">
                      <p class="error"></p>
                      <label for="uncroppedPic">Upload a picture</label>
                      <input type="file" id="uncroppedPic" name="uncroppedPic"  accept="image/*">
                      <p class="help-block">Please selct an image of dimensions less than 600x600px.</p>
                      <input type="submit" class="btn btn-default" value="UPLOAD" />
                    </div>
                  </form>

                </div>
              </div>

                <div class="row">
                  <p class="target_p">
                    <img id="target" src="" class="img-responsive" />
                  </p>
                </div>
            </div>
            <div class="modal-footer">
              <input type="button" class="btn btn-success cropSubmit" value="Make this my profile pic!">
              <button type="button" class="btn btn-primary modal-close" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

{% endblock %}
{% block container_title %}<h1 style="color: black">Edit Profile</h1> <span class="formError" style="font-size: 15px;color: darkred;display: none;visibility: hidden">Please enter the required fields.</span><hr>{% endblock %}

{% block container_block %}

    <form class="cbp-mc-form form" method="post" action="/mentee/edit-profile/">
    {% csrf_token %}
    <input type="hidden" id="x1" name="x1" value="" />
    <input type="hidden" id="x2" name="x2" value="" />
    <input type="hidden" id="y1" name="y1" value="" />
    <input type="hidden" id="y2" name="y2" value="" />
    <input type="hidden" id="w" name="w" value="" />
    <input type="hidden" id="h" name="h" value="" />

	<div class="cbp-mc-column">
		{% for field in user_form %}
                {{ field.label_tag }}
                {{ field|add_class:"required" }}
        {% endfor %}
        {{ profile_form.about.label_tag }}
        {{ profile_form.about }}


	</div>
	<div class="cbp-mc-column">
        <label for="id_picture">Profile Image</label>
        <img src="{{ profile_form.picture.value }}" class="img-circle center edit-pic" />
        {{ profile_form.picture }}
        <button class="btn btn-primary mg-left-s modalOpener" type="button">Upload new</button>
        {{ profile_form.gender.label_tag }}
        {{ profile_form.gender|add_class:"required" }}


        {{ profile_form.date_of_birth.label_tag }}
        {{ profile_form.date_of_birth|add_class:"required" }}


        {{ profile_form.contact.label_tag }}
        {{ profile_form.contact }}

	</div>
	<div class="cbp-mc-column">
        {{ profile_form.college.label_tag }}
        {{ profile_form.college|add_class:"required" }}

        {{ profile_form.city.label_tag }}
        {{ profile_form.city|add_class:"required" }}

        {{ profile_form.state.label_tag }}
        {{ profile_form.state }}

        {{ profile_form.country.label_tag }}
        {{ profile_form.country|add_class:"required" }}

	</div>
	<div class="cbp-mc-submit-wrap"><input class="cbp-mc-submit" type="button" value="Update" /></div>
    <div class="modal"><!-- Place at bottom of page --></div>
</form>


{% endblock %}
{%  block scripts %}
<script src="{% static 'datepicker/js/bootstrap-datepicker.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/jcrop/jquery.imgareaselect.pack.js' %}"></script>
<script>
        $body = $("body");
        $(document).on({
            ajaxStart: function() { $body.addClass("loading");    },
             ajaxStop: function() { $body.removeClass("loading"); }
        });

        $(".formError").hide();
        function validate() {
            var valid = 1;
            $(".required").each(function (i, obj) {
                if ($(this).val().trim() == '') {
                    valid *= 0;
                    $(this).css({"border": "1px solid red"});
                }
            });
            return valid;
        }
        $('#id_date_of_birth').datepicker({
            format: 'mm/dd/yyyy'
        });
        $(".form").submit(function(e) {
            e.preventDefault();
            submit();
        });
        $(".cbp-mc-submit").click(function() {
            submit();
        });

        function submit() {
            var valid = validate();
            if(valid == 1) {
                $.ajax({
                    url: "/mentee/edit-profile/",
                    type: "post",
                    data: $(".form").serializeArray(),
                    dataType: "json",
                    success: function(data) {
                        if(data['error']==true) {
                            $(".formError").html("Failed to update profile");
                        }
                        else {
                            $(".formError").html("Profile Successfully updated!");
                            $(".formError").css({"color": "white"});
                            location.reload();

                        }
                    }
                });

            } else {
                $(".formError").html("Please enter the required fields.");
                $(".formError").css({"color": "darkred"});
                $(".formError").show();
                swal({
                    title: "Oops",
                    html: "Please enter all the required fields",
                    showConfirmButton: false,
                    showCancelButton: false,
                    type: 'error'
                 });
            }
        }

        var ias; // Stores Instance of ImageAreaSelect
        $(document).ready(function() {
          $('.cropSubmit').hide();
        });
        $(document).ready(function() {
          $('.passHelp').hide();
        });
        $(document).ready(function() {
          $('input[type=password]').focus(function() {
              $('.passHelp').show();
          });
        });




        function preview(img, selection) {
            var scaleX = 100 / (selection.width || 1);
            var scaleY = 100 / (selection.height || 1);

            var image = document.getElementById('target');

            $('#x1').val(selection.x1);
            $('#y1').val(selection.y1);
            $('#x2').val(selection.x2);
            $('#y2').val(selection.y2);
            $('#w').val(selection.width);
            $('#h').val(selection.height);

            var scaleX = 100 / selection.width;
            var scaleY = 100 / selection.height;


            var tarImg  =document.getElementById('target');

            $('#id_picture').css({
                width: Math.round(scaleX * tarImg.naturalWidth),
                height: Math.round(scaleY * tarImg.naturalHeight),
                marginLeft: -Math.round(scaleX * selection.x1),
                marginTop: -Math.round(scaleY * selection.y1)
            });

            if(tarImg.naturalHeight > 400 || tarImg.naturalWidth >400) {
              $('#preview2').remove();
            }

            if(selection.width == 0) {
              $(".cropSubmit").hide();
            }
            else {
             $(".cropSubmit").show();
            }
        }


         //Program a custom submit function for the form
          $("#uploadForm").submit(function(event){

            //disable the default form submission
            event.preventDefault();

            //grab all form data
            var formData = new FormData($(this)[0]);

            if($('#uncroppedPic').val() == '') {
              $('#cropModal .error').html("Please select an Image to upload.");
              return;
            }

              $.ajax({
                url: '/user/save-image/',
                type: 'POST',
                data: formData,
                async: false,
                cache: false,
                contentType: false,
                processData: false,
                success: function (returndata) {
                  if(returndata === 'failed') {
                      $('#cropModal .error').html("Please check the image type.<br>Only JPG/JPEG,PNG,GIFs are allowed!");
                      return;
                  }
                  $('#target').attr("src",returndata);

                  $('#target').css("display","block");
                  $('#target').css("visibility","visible");


                  var image = document.getElementById('target');


                  var pic_real_width, pic_real_height;
                  $("<img/>") // Make in memory copy of image to avoid css issues
                      .attr("src", $(image).attr("src"))
                      .load(function() {
                          pic_real_width = this.width;   // Note: $(this).width() will not
                          pic_real_height = this.height; // work for in memory images.

                          ias = $('#target').imgAreaSelect({
                          aspectRatio: '1:1',
                          handles: true,
                          fadeSpeed: 200,
                          onSelectChange: preview,
                          imageWidth: pic_real_width,
                          imageHeight: pic_real_height,
                          maxHeight: 400,
                          maxWidth: 400,
                          instance: true
                        });
                        $('.cropSubmit').show();
                      });
                }
              });
        });


        $('.modal-close').click(function() {
          ias.cancelSelection();
        });

        //Program a custom submit function for the form
          $(".cropSubmit").click(function(event){
            //disable the default form submission
            event.preventDefault();

            //grab all form data
            var input = $("<input>")
               .attr("type", "hidden")
               .attr("name", "url").val($('#target').attr('src'));
            $('.form').append($(input));

            $(".modal-close")[0].click();
        });

    $(".modalOpener").click(function() {
       $("#cropModal").modal('show');
    });

    </script>

{%  endblock %}

templates/mentee/index.html
{% extends 'mentee/base.html' %}
{% load static %}

{% block body_block %}

This is index page!

{% endblock %}

templates/mentee/manage-social-profiles.html
{% extends 'mentee/base.html' %}
{% load static %}
{%  block stylesheets %}
    <style type="text/css">
        .textCenter {
            text-align: center;
        }
        .btn-round {
              background-color: #ffa54f;
              border-radius: 999em;
              width: 50px;
              height: 50px;
              box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.26);
              line-height: 1;
              font-size: 36px;
              position: relative;
              cursor: pointer;
              display: block;
              margin: 5px auto;
            }

            .btn-round i {
                position: absolute;
              left: 0;
              top: 70%;
              height: 100%;
              width: 100%;
              text-align: center;
              margin-top: -22px;
              color: #FFF;
                font-size: 25px;
            }
            .center {
                display: block;
                margin: 0 auto;
            }
            .img-responsive {
                max-width: 100px;
                max-height: 100px;
            }
    </style>
{%  endblock %}

{% block container_title %}<div class="col-xs-12 textCenter"><h1 class="center">Manage Social Profiles</h1></div><br>{% endblock %}

{% block container_block %}
    <div class="col-md-4 col-sm-6 spacing-bottom-sm spacing-bottom">
        <div class="tiles white added-margin textCenter">
            <div class="tiles-body">
                <h2>Google</h2>
                <hr>
                <div class="btn-round" style="background-color: #dd4b39"><i class="fa fa-google-plus"></i></div>
                {% if sp != None and sp.profile_url_google != ""%}
                    <hr>
                    Avatar: <img style="width: 100px;height: 100px" class="img-responsive center" src="{{ sp.profile_pic_url_google }}"></img><br>
                    <a href="{{ sp.profile_url_google }}">Profile URL</a><br>
                    <a href="/mentee/manage-social-profiles/remove/google/">Remove</a>
                {% else %}
                    <a href='{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}'>Link an account!</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 spacing-bottom-sm spacing-bottom">
        <div class="tiles white added-margin textCenter">
            <div class="tiles-body">
                <h2>Facebook</h2>
                <hr>
                <div class="btn-round" style="background-color: #3b5998"><i class="fa fa-facebook"></i></div>

                {% if sp != None and sp.profile_url_facebook != "" %}
                    <hr>
                    Avatar: <img style="width: 100px;height: 100px" class="img-responsive center" src="{{ sp.profile_pic_url_facebook }}"></img><br>
                    <a href="{{ sp.profile_url_facebook }}">Profile URL</a><br>
                    <a href="/mentee/manage-social-profiles/remove/facebook/">Remove</a>
                {% else %}
                    <a href='{% url 'social:begin' 'facebook' %}?next={{ request.path }}'>Link an account!</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4 col-sm-6 spacing-bottom-sm spacing-bottom">
        <div class="tiles white added-margin textCenter">
            <div class="tiles-body">
                <h2>Linkedin</h2>
                <hr>
                <div class="btn-round" style="background-color: #0976b4"><i class="fa fa-linkedin"></i></div>

                {% if sp != None and sp.profile_url_linkedin != "" %}
                    <hr>
                    Avatar: <img style="width: 100px;height: 100px" class="img-responsive center" src="{{ sp.profile_pic_url_linkedin }}"></img><br>
                    <a href="{{ sp.profile_url_linkedin }}">Profile URL</a><br>
                    <a href="/mentee/manage-social-profiles/remove/linkedin/">Remove</a>
                {% else %}
                    <a href='{% url 'social:begin' 'linkedin-oauth2' %}?next={{ request.path }}'>Link an accont</a>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-10 col-md-offset-1 spacing-bottom-sm spacing-bottom">
        <div class="tiles white">
            <div class="tiles-body">
                Note: The email with which you have registered your Facebook, Google or LinkedIn account
                should be same as the one you are using on MentorBuddy.
            </div>
        </div>
    </div>
{% endblock %}

templates/mentee/search_root.html
{% extends 'mentee/base.html' %}
{% load static %}
{%  block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/mentee/search.css' %} " type="text/css" />
{% endblock %}

{%  block container_title %}
<h1>Search Results</h1>
{% endblock %}
{% block container_block %}

    {% if subcategory == None %}
        <div class="tiles info">Your query "{{ search_query }}" has returned {{ mentors.count }} result{{ mentors|pluralize }}</div>
    {% else %}
        <div class="tiles info">Mentors in category - {{ subcategory }}</div>
    {% endif %}

    <div class="pad-bottom-50">
        <div class="row">
            {% for mentor in mentors %}
                 <div class="col-md-4 textCenter margin-top-mid">
                     <div class="tiles white textCenter">
                         <img src="{{ mentor.picture }}" class="img-circle img-responsive"/>
                         <h3><a href="/mentor/get-profile/{{ mentor.id }}/">{{ mentor.first_name }} {{ mentor.last_name}}</a></h3>
                         {% if 'type' not in mentor %}
                             {% if mentor.college %}
                                 {{ mentor.college }}
                                 <br>
                             {% else %}
                                 College not specified<br>
                             {% endif %}
                         {% else %}
                             {% if mentor.emp != None %}
                                 {% if mentor.emp.position != None %}
                                    {{ mentor.emp.position }}
                                 {% endif %}
                                 {%  if mentor.emp.organization != None %}
                                     at {{ mentor.emp.organization }}
                                     <br>
                                 {% endif %}
                             {% endif %}
                         {% endif %}
                         {{ mentor.city }},
                         {{ mentor.country }}
                     </div>
                 </div>
             {% endfor %}
        </div>
    </div>
{% endblock %}


{% block scripts %}
{% endblock %}